# Generated by Django 3.2.8 on 2021-11-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('dow_one', models.TextField(max_length=20)),
                ('dow_two', models.TextField(blank=True, max_length=20)),
                ('dow_three', models.TextField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_first_name', models.TextField(max_length=20)),
                ('r_last_name', models.TextField(max_length=20)),
                ('r_other_identifier', models.TextField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actiscribe.activity')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actiscribe.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actiscribe.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(blank=True, max_length=20)),
                ('games_yn', models.TextField(blank=True, max_length=50)),
                ('books_yn', models.TextField(blank=True, max_length=50)),
                ('music_yn', models.TextField(blank=True, max_length=50)),
                ('crafts_yn', models.TextField(blank=True, max_length=50)),
                ('arts_yn', models.TextField(blank=True, max_length=50)),
                ('learning_yn', models.TextField(blank=True, max_length=50)),
                ('gardening_yn', models.TextField(blank=True, max_length=50)),
                ('sports_yn', models.TextField(blank=True, max_length=50)),
                ('exercise_yn', models.TextField(blank=True, max_length=50)),
                ('outside_yn', models.TextField(blank=True, max_length=50)),
                ('animals_yn', models.TextField(blank=True, max_length=50)),
                ('socializing_yn', models.TextField(blank=True, max_length=50)),
                ('work', models.TextField(blank=True, max_length=250)),
                ('volunteer', models.TextField(blank=True, max_length=250)),
                ('parents', models.TextField(blank=True, max_length=250)),
                ('siblings', models.TextField(blank=True, max_length=250)),
                ('close_family', models.TextField(blank=True, max_length=250)),
                ('spouse', models.TextField(blank=True, max_length=250)),
                ('children', models.TextField(blank=True, max_length=250)),
                ('technology', models.TextField(blank=True, max_length=250)),
                ('city_or_country', models.TextField(blank=True, max_length=250)),
                ('travel', models.TextField(blank=True, max_length=250)),
                ('alone_fun', models.TextField(blank=True, max_length=250)),
                ('social_fun', models.TextField(blank=True, max_length=250)),
                ('one_thing', models.TextField(blank=True, max_length=250)),
                ('resident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actiscribe.resident')),
            ],
        ),
    ]
