# Generated by Django 3.2.8 on 2021-11-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actiscribe', '0004_auto_20211103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='actiscribe.activity'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='actiscribe.resident'),
        ),
    ]
